#!/bin/sh

ENABLED=$(uci get ipt_ttl.config.enabled)
TTL=$(uci get ipt_ttl.config.ttl)
echo "# Generated by luci-app-ipt-ttl" > /etc/firewall.user

if [ "$ENABLED" = "0" ]; then
    {
        echo "iptables -t mangle -A PREROUTING -j TTL --ttl-set $TTL"
        echo "iptables -t mangle -A POSTROUTING -j TTL --ttl-set $TTL"
        echo "ip6tables -t mangle -A PREROUTING -i wwan0 -j HL --hl-set $TTL"
        echo "ip6tables -t mangle -A POSTROUTING -o wwan0 -j HL --hl-set $TTL"
        echo "ip6tables -t mangle -A PREROUTING -i wwan0_1 -j HL --hl-set $TTL"
        echo "ip6tables -t mangle -A POSTROUTING -o wwan0_1 -j HL --hl-set $TTL"
    } >> /etc/firewall.user
fi
